name: cookbook-gc
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopy
  - jupyter-book
  - jupyterlab
  - matplotlib
  - mystmd
  - numpy
  - pyproj
  - sphinx-pythia-theme
  - uxarray
  - pip
  - pip:
      - jupyterlab-myst
