name: cookbook-gc
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - numpy
  - uxarray
  - geopy
  - pyproj
  - matplotlib
  - cartopy
  - pip
  - pip:
      - jupyterlab-myst
